import type { DocumentoGestionale } from "@/lib/types/gestionale";

/** Macchina in anagrafica documenti (demo). */
export interface CatalogMacchina {
  id: string;
  nome: string;
}

/** Marca in anagrafica documenti (demo). */
export interface CatalogMarca {
  id: string;
  nome: string;
  macchine: CatalogMacchina[];
}

/**
 * Catalogo demo legacy (non più usato in UI): marche e modelli provengono da Impostazioni mezzi + anagrafica.
 * Mantenuto vuoto per evitare divergenza rispetto ai dati reali del gestionale.
 */
export const INITIAL_DOCUMENTI_CATALOG: CatalogMarca[] = [];

/**
 * Mock allineati a `lib/mock-data/mezzi.ts` (nomi marca/modello come in anagrafica e liste dashboard).
 */
export const MOCK_DOCUMENTI: DocumentoGestionale[] = [
  {
    id: "doc-1",
    nome: "Manuale uso e manutenzione.pdf",
    categoria: "manuali",
    applicabilita: "modello",
    marcaKey: "Mercedes-Benz",
    modelloKey: "Econic 1829",
    marca: "Mercedes-Benz",
    macchina: "Econic 1829",
    tipoFile: "pdf",
    autoreCaricamento: "Admin",
    note: "Edizione officina 2025",
    caricatoIl: "2026-04-02",
    ultimaModifica: "2026-04-10",
    dimensioneKb: 4200,
    urlDocumento: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
  },
  {
    id: "doc-2",
    nome: "Listino 2026.xlsx",
    categoria: "listini",
    applicabilita: "marca",
    marcaKey: "Mercedes-Benz",
    marca: "Mercedes-Benz",
    macchina: "—",
    tipoFile: "excel",
    autoreCaricamento: "Operatore CAB",
    caricatoIl: "2026-03-28",
    ultimaModifica: "2026-03-28",
    dimensioneKb: 890,
  },
  {
    id: "doc-3",
    nome: "Catalogo ricambi.pdf",
    categoria: "cataloghi",
    applicabilita: "modello",
    marcaKey: "Iveco",
    modelloKey: "Daily 70C15",
    marca: "Iveco",
    macchina: "Daily 70C15",
    tipoFile: "pdf",
    autoreCaricamento: "Admin",
    caricatoIl: "2026-05-01",
    ultimaModifica: "2026-05-01",
    dimensioneKb: 12500,
  },
  {
    id: "doc-4",
    nome: "Scheda tecnica Eurocargo.pdf",
    categoria: "manuali",
    applicabilita: "modello",
    marcaKey: "Iveco",
    modelloKey: "Eurocargo ML120",
    marca: "Iveco",
    macchina: "Eurocargo ML120",
    tipoFile: "pdf",
    autoreCaricamento: "Operatore CAB",
    note: "Rev. 3",
    caricatoIl: "2026-04-18",
    ultimaModifica: "2026-04-22",
    dimensioneKb: 3100,
  },
  {
    id: "doc-5",
    nome: "Listino ricambi Midlum.xlsx",
    categoria: "listini",
    applicabilita: "marca",
    marcaKey: "Renault",
    marca: "Renault",
    macchina: "—",
    tipoFile: "excel",
    autoreCaricamento: "Admin",
    caricatoIl: "2026-03-15",
    ultimaModifica: "2026-03-15",
    dimensioneKb: 2100,
  },
  {
    id: "doc-6",
    nome: "Manuale operatore FE.pdf",
    categoria: "manuali",
    applicabilita: "modello",
    marcaKey: "Volvo",
    modelloKey: "FE 320",
    marca: "Volvo",
    macchina: "FE 320",
    tipoFile: "pdf",
    autoreCaricamento: "Operatore CAB",
    caricatoIl: "2026-02-20",
    ultimaModifica: "2026-02-20",
    dimensioneKb: 5600,
  },
  {
    id: "doc-7",
    nome: "Catalogo P 320 2026.pdf",
    categoria: "cataloghi",
    applicabilita: "modello",
    marcaKey: "Scania",
    modelloKey: "P 320",
    marca: "Scania",
    macchina: "P 320",
    tipoFile: "pdf",
    autoreCaricamento: "Admin",
    caricatoIl: "2026-05-06",
    ultimaModifica: "2026-05-06",
    dimensioneKb: 9800,
  },
  {
    id: "doc-8",
    nome: "Note interne fornitore.txt",
    categoria: "altro",
    applicabilita: "modello",
    marcaKey: "Isuzu",
    modelloKey: "NPR 75",
    marca: "Isuzu",
    macchina: "NPR 75",
    tipoFile: "testo",
    autoreCaricamento: "Operatore CAB",
    note: "Riferimento ordine demo",
    caricatoIl: "2026-04-01",
    ultimaModifica: "2026-04-05",
    dimensioneKb: 12,
  },
  {
    id: "doc-9a",
    nome: "Manuale circuito idraulico comune.pdf",
    categoria: "manuali",
    applicabilita: "modello",
    marcaKey: "Iveco",
    modelloKey: "Daily 70C15",
    marca: "Iveco",
    macchina: "Daily 70C15",
    tipoFile: "pdf",
    autoreCaricamento: "Admin",
    note: "Versione condivisa (Daily 70C15)",
    caricatoIl: "2026-05-08",
    ultimaModifica: "2026-05-08",
    dimensioneKb: 2400,
  },
  {
    id: "doc-9b",
    nome: "Manuale circuito idraulico comune.pdf",
    categoria: "manuali",
    applicabilita: "modello",
    marcaKey: "Iveco",
    modelloKey: "Eurocargo ML120",
    marca: "Iveco",
    macchina: "Eurocargo ML120",
    tipoFile: "pdf",
    autoreCaricamento: "Admin",
    note: "Versione condivisa (Eurocargo)",
    caricatoIl: "2026-05-08",
    ultimaModifica: "2026-05-08",
    dimensioneKb: 2400,
  },
  {
    id: "doc-9c",
    nome: "Manuale circuito idraulico comune.pdf",
    categoria: "manuali",
    applicabilita: "modello",
    marcaKey: "Mercedes-Benz",
    modelloKey: "Atego 1524",
    marca: "Mercedes-Benz",
    macchina: "Atego 1524",
    tipoFile: "pdf",
    autoreCaricamento: "Admin",
    note: "Versione condivisa (Atego)",
    caricatoIl: "2026-05-08",
    ultimaModifica: "2026-05-08",
    dimensioneKb: 2400,
  },
  {
    id: "doc-10",
    nome: "Checklist post-intervento (mezzo).pdf",
    categoria: "manuali",
    applicabilita: "macchina",
    marcaKey: "Mercedes-Benz",
    modelloKey: "Econic 1829",
    mezzoId: "mezzo-07",
    marca: "Mercedes-Benz",
    macchina: "Econic 1829",
    tipoFile: "pdf",
    autoreCaricamento: "Operatore CAB",
    caricatoIl: "2026-05-09",
    ultimaModifica: "2026-05-09",
    dimensioneKb: 180,
    urlDocumento: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
  },
];
