import type { RicambioMagazzino } from "@/lib/magazzino/types";
import { prezzoVenditaDaListinoEMarkup } from "@/lib/magazzino/calculations";

const now = "2026-05-10T10:00:00.000Z";

/** Coerenza listino × (1 + markup%) → prezzo vendita (arrotondato). */
function rv(listino: number, markupPercentuale: number): number {
  return prezzoVenditaDaListinoEMarkup(listino, markupPercentuale);
}

export const MOCK_RICAMBI: RicambioMagazzino[] = [
  {
    id: "r01",
    marca: "Donaldson",
    codiceFornitoreOriginale: "P821575",
    descrizione: "Filtro aria primario aspirazione street sweeper",
    note: "Per aspirazione ad alto flusso",
    categoria: "Filtrazione",
    compatibilitaMezzi: ["Schmidt Cleango 500", "Dulevo 6000", "Iveco Daily 70C"],
    scorta: 18,
    scortaMinima: 6,
    dataUltimaModifica: now,
    autoreUltimaModifica: "Admin",
    prezzoFornitoreOriginale: 118.5,
    scontoFornitoreOriginale: 12,
    markupPercentuale: 59.49,
    prezzoVendita: rv(118.5, 59.49),
    fornitoreNonOriginale: "Mann-Filter",
    codiceFornitoreNonOriginale: "C 25 024",
    prezzoFornitoreNonOriginale: 96.0,
    scontoFornitoreNonOriginale: 8,
  },
  {
    id: "r02",
    marca: "Bosch",
    codiceFornitoreOriginale: "F 026 400 492",
    descrizione: "Filtro gasolio Common Rail",
    note: "",
    categoria: "Filtrazione",
    compatibilitaMezzi: ["Mercedes Actros", "Iveco Eurocargo", "Iveco Daily"],
    scorta: 4,
    scortaMinima: 8,
    dataUltimaModifica: now,
    autoreUltimaModifica: "Admin",
    prezzoFornitoreOriginale: 42.3,
    scontoFornitoreOriginale: 15,
    markupPercentuale: 71.39,
    prezzoVendita: rv(42.3, 71.39),
    fornitoreNonOriginale: "UFI Filters",
    codiceFornitoreNonOriginale: "24.ONE.01",
    prezzoFornitoreNonOriginale: 35.9,
    scontoFornitoreNonOriginale: 10,
  },
  {
    id: "r03",
    marca: "SKF",
    codiceFornitoreOriginale: "VKBA 6631",
    descrizione: "Kit cuscinetto ruota anteriore",
    note: "Include dado autobloccante",
    categoria: "Trasmissione",
    compatibilitaMezzi: ["Iveco Daily 35-70C", "Mercedes Sprinter"],
    scorta: 12,
    scortaMinima: 4,
    dataUltimaModifica: now,
    autoreUltimaModifica: "Admin",
    prezzoFornitoreOriginale: 86.0,
    scontoFornitoreOriginale: 18,
    markupPercentuale: 65.12,
    prezzoVendita: rv(86.0, 65.12),
    fornitoreNonOriginale: "SNR",
    codiceFornitoreNonOriginale: "R154.63",
    prezzoFornitoreNonOriginale: 74.5,
    scontoFornitoreNonOriginale: 12,
  },
  {
    id: "r04",
    marca: "Bosch Rexroth",
    codiceFornitoreOriginale: "R902501346",
    descrizione: "Pompa idraulica assiale 45 cc",
    note: "Revisionabile",
    categoria: "Idraulica",
    compatibilitaMezzi: ["Bucher CityCat 2020", "Faun Viajet 6"],
    scorta: 2,
    scortaMinima: 2,
    dataUltimaModifica: now,
    autoreUltimaModifica: "Admin",
    prezzoFornitoreOriginale: 1840.0,
    scontoFornitoreOriginale: 10,
    markupPercentuale: 44.02,
    prezzoVendita: rv(1840.0, 44.02),
    fornitoreNonOriginale: "Parker Hannifin",
    codiceFornitoreNonOriginale: "P2075R",
    prezzoFornitoreNonOriginale: 1620.0,
    scontoFornitoreNonOriginale: 7,
  },
  {
    id: "r05",
    marca: "Iveco",
    codiceFornitoreOriginale: "504102851",
    descrizione: "Pastiglie freno anteriori originali",
    note: "",
    categoria: "Freni",
    compatibilitaMezzi: ["Iveco Daily", "Iveco Eurocargo"],
    scorta: 14,
    scortaMinima: 6,
    dataUltimaModifica: now,
    autoreUltimaModifica: "Admin",
    prezzoFornitoreOriginale: 128.0,
    scontoFornitoreOriginale: 14,
    markupPercentuale: 54.69,
    prezzoVendita: rv(128.0, 54.69),
    fornitoreNonOriginale: "Brembo",
    codiceFornitoreNonOriginale: "P 68 089",
    prezzoFornitoreNonOriginale: 98.0,
    scontoFornitoreNonOriginale: 9,
  },
  {
    id: "r06",
    marca: "Mercedes-Benz",
    codiceFornitoreOriginale: "A0004209920",
    descrizione: "Disco freno ventilato posteriore",
    note: "Coppia consigliata",
    categoria: "Freni",
    compatibilitaMezzi: ["Mercedes Actros", "Mercedes Atego"],
    scorta: 6,
    scortaMinima: 4,
    dataUltimaModifica: now,
    autoreUltimaModifica: "Admin",
    prezzoFornitoreOriginale: 310.0,
    scontoFornitoreOriginale: 11,
    markupPercentuale: 46.77,
    prezzoVendita: rv(310.0, 46.77),
    fornitoreNonOriginale: "Textar",
    codiceFornitoreNonOriginale: "92123400",
    prezzoFornitoreNonOriginale: 268.0,
    scontoFornitoreNonOriginale: 8,
  },
  {
    id: "r07",
    marca: "Valeo",
    codiceFornitoreOriginale: "837039",
    descrizione: "Frizione completa con spingidisco",
    note: "",
    categoria: "Trasmissione",
    compatibilitaMezzi: ["Iveco Daily", "Iveco Eurocargo"],
    scorta: 3,
    scortaMinima: 2,
    dataUltimaModifica: now,
    autoreUltimaModifica: "Admin",
    prezzoFornitoreOriginale: 520.0,
    scontoFornitoreOriginale: 16,
    markupPercentuale: 50,
    prezzoVendita: rv(520.0, 50),
    fornitoreNonOriginale: "Sachs",
    codiceFornitoreNonOriginale: "3000 951 987",
    prezzoFornitoreNonOriginale: 465.0,
    scontoFornitoreNonOriginale: 12,
  },
  {
    id: "r08",
    marca: "Continental",
    codiceFornitoreOriginale: "8PK 1920",
    descrizione: "Cinghia servizi poly-V 8 nervature",
    note: "Controlare tenditore",
    categoria: "Trasmissione",
    compatibilitaMezzi: ["Mercedes Actros", "Iveco Stralis"],
    scorta: 22,
    scortaMinima: 10,
    dataUltimaModifica: now,
    autoreUltimaModifica: "Admin",
    prezzoFornitoreOriginale: 38.9,
    scontoFornitoreOriginale: 20,
    markupPercentuale: 65.81,
    prezzoVendita: rv(38.9, 65.81),
    fornitoreNonOriginale: "Gates",
    codiceFornitoreNonOriginale: "8PK1920",
    prezzoFornitoreNonOriginale: 32.4,
    scontoFornitoreNonOriginale: 15,
  },
  {
    id: "r09",
    marca: "Hella",
    codiceFornitoreOriginale: "1GA 996 176-041",
    descrizione: "Faro LED lavoro laterale 12/24V",
    note: "Omologazione ECE R10",
    categoria: "Elettronica",
    compatibilitaMezzi: ["Iveco Daily", "Mercedes Atego", "Schmidt Cleango 500"],
    scorta: 16,
    scortaMinima: 6,
    dataUltimaModifica: now,
    autoreUltimaModifica: "Admin",
    prezzoFornitoreOriginale: 95.0,
    scontoFornitoreOriginale: 14,
    markupPercentuale: 63.16,
    prezzoVendita: rv(95.0, 63.16),
    fornitoreNonOriginale: "LED Autolamps",
    codiceFornitoreNonOriginale: "LA-8820",
    prezzoFornitoreNonOriginale: 72.0,
    scontoFornitoreNonOriginale: 10,
  },
  {
    id: "r10",
    marca: "Wabco",
    codiceFornitoreOriginale: "9325001100",
    descrizione: "Valvola modulante ABS/EBS",
    note: "Calibrazione banco prova",
    categoria: "Freni",
    compatibilitaMezzi: ["Mercedes Actros", "Iveco Stralis"],
    scorta: 5,
    scortaMinima: 3,
    dataUltimaModifica: now,
    autoreUltimaModifica: "Admin",
    prezzoFornitoreOriginale: 410.0,
    scontoFornitoreOriginale: 9,
    markupPercentuale: 43.9,
    prezzoVendita: rv(410.0, 43.9),
    fornitoreNonOriginale: "Knorr-Bremse",
    codiceFornitoreNonOriginale: "K000087",
    prezzoFornitoreNonOriginale: 385.0,
    scontoFornitoreNonOriginale: 7,
  },
  {
    id: "r11",
    marca: "Parker",
    codiceFornitoreOriginale: "D1VW020CNJW",
    descrizione: "Valvola idraulica direzionale NG6",
    note: "",
    categoria: "Idraulica",
    compatibilitaMezzi: ["Bucher CityCat", "Dulevo 6000"],
    scorta: 7,
    scortaMinima: 4,
    dataUltimaModifica: now,
    autoreUltimaModifica: "Admin",
    prezzoFornitoreOriginale: 156.0,
    scontoFornitoreOriginale: 12,
    markupPercentuale: 57.05,
    prezzoVendita: rv(156.0, 57.05),
    fornitoreNonOriginale: "Hydac",
    codiceFornitoreNonOriginale: "4WE 6 J62",
    prezzoFornitoreNonOriginale: 138.0,
    scontoFornitoreNonOriginale: 8,
  },
  {
    id: "r12",
    marca: "Donaldson",
    codiceFornitoreOriginale: "P550949",
    descrizione: "Filtro olio idraulico spin-on",
    note: "",
    categoria: "Filtrazione",
    compatibilitaMezzi: ["Faun Viajet", "Bucher CityCat", "Mercedes Actros"],
    scorta: 28,
    scortaMinima: 12,
    dataUltimaModifica: now,
    autoreUltimaModifica: "Admin",
    prezzoFornitoreOriginale: 34.5,
    scontoFornitoreOriginale: 22,
    markupPercentuale: 68.12,
    prezzoVendita: rv(34.5, 68.12),
    fornitoreNonOriginale: "Fleetguard",
    codiceFornitoreNonOriginale: "HF35375",
    prezzoFornitoreNonOriginale: 28.9,
    scontoFornitoreNonOriginale: 18,
  },
  {
    id: "r13",
    marca: "SKF",
    codiceFornitoreOriginale: "CR 135x160x12 HMSA10 RG",
    descrizione: "Paraolio albero pompa idraulica",
    note: "Lubrificare al montaggio",
    categoria: "Tenute",
    compatibilitaMezzi: ["Bucher CityCat", "Schmidt Cleango"],
    scorta: 20,
    scortaMinima: 8,
    dataUltimaModifica: now,
    autoreUltimaModifica: "Admin",
    prezzoFornitoreOriginale: 18.6,
    scontoFornitoreOriginale: 25,
    markupPercentuale: 72.04,
    prezzoVendita: rv(18.6, 72.04),
    fornitoreNonOriginale: "Freudenberg",
    codiceFornitoreNonOriginale: "BAUM7X12",
    prezzoFornitoreNonOriginale: 15.2,
    scontoFornitoreNonOriginale: 15,
  },
  {
    id: "r14",
    marca: "VDO",
    codiceFornitoreOriginale: "A2C59506225",
    descrizione: "Sensore pressione common rail",
    note: "",
    categoria: "Elettronica",
    compatibilitaMezzi: ["Iveco Daily", "Iveco Eurocargo"],
    scorta: 9,
    scortaMinima: 5,
    dataUltimaModifica: now,
    autoreUltimaModifica: "Admin",
    prezzoFornitoreOriginale: 76.0,
    scontoFornitoreOriginale: 13,
    markupPercentuale: 63.16,
    prezzoVendita: rv(76.0, 63.16),
    fornitoreNonOriginale: "Delphi",
    codiceFornitoreNonOriginale: "28437251",
    prezzoFornitoreNonOriginale: 68.0,
    scontoFornitoreNonOriginale: 10,
  },
  {
    id: "r15",
    marca: "Mahle",
    codiceFornitoreOriginale: "OC 510",
    descrizione: "Filtro olio motore",
    note: "",
    categoria: "Filtrazione",
    compatibilitaMezzi: ["Mercedes Atego", "Mercedes Actros"],
    scorta: 3,
    scortaMinima: 10,
    dataUltimaModifica: now,
    autoreUltimaModifica: "Admin",
    prezzoFornitoreOriginale: 22.4,
    scontoFornitoreOriginale: 18,
    markupPercentuale: 71.88,
    prezzoVendita: rv(22.4, 71.88),
    fornitoreNonOriginale: "Mann-Filter",
    codiceFornitoreNonOriginale: "HU 7008 Z",
    prezzoFornitoreNonOriginale: 19.8,
    scontoFornitoreNonOriginale: 12,
  },
  {
    id: "r16",
    marca: "Bosch",
    codiceFornitoreOriginale: "0 281 006 028",
    descrizione: "Iniettore Common Rail rigenerato",
    note: "Test su banco incluso",
    categoria: "Motore",
    compatibilitaMezzi: ["Iveco Daily", "Iveco Eurocargo"],
    scorta: 2,
    scortaMinima: 2,
    dataUltimaModifica: now,
    autoreUltimaModifica: "Admin",
    prezzoFornitoreOriginale: 285.0,
    scontoFornitoreOriginale: 8,
    markupPercentuale: 47.37,
    prezzoVendita: rv(285.0, 47.37),
    fornitoreNonOriginale: "Delphi",
    codiceFornitoreNonOriginale: "R00301D",
    prezzoFornitoreNonOriginale: 240.0,
    scontoFornitoreNonOriginale: 6,
  },
  {
    id: "r17",
    marca: "Iveco",
    codiceFornitoreOriginale: "504046367",
    descrizione: "Termostato 83°C",
    note: "",
    categoria: "Motore",
    compatibilitaMezzi: ["Iveco Daily", "Iveco Eurocargo"],
    scorta: 11,
    scortaMinima: 5,
    dataUltimaModifica: now,
    autoreUltimaModifica: "Admin",
    prezzoFornitoreOriginale: 48.0,
    scontoFornitoreOriginale: 16,
    markupPercentuale: 64.58,
    prezzoVendita: rv(48.0, 64.58),
    fornitoreNonOriginale: "Wahler",
    codiceFornitoreNonOriginale: "4105.83D",
    prezzoFornitoreNonOriginale: 39.5,
    scontoFornitoreNonOriginale: 12,
  },
  {
    id: "r18",
    marca: "Mercedes-Benz",
    codiceFornitoreOriginale: "A9064700190",
    descrizione: "Intercooler aria",
    note: "Verificare supporti gomma",
    categoria: "Motore",
    compatibilitaMezzi: ["Mercedes Sprinter", "Mercedes Atego"],
    scorta: 1,
    scortaMinima: 2,
    dataUltimaModifica: now,
    autoreUltimaModifica: "Admin",
    prezzoFornitoreOriginale: 890.0,
    scontoFornitoreOriginale: 7,
    markupPercentuale: 32.58,
    prezzoVendita: rv(890.0, 32.58),
    fornitoreNonOriginale: "Nissens",
    codiceFornitoreNonOriginale: "96590",
    prezzoFornitoreNonOriginale: 720.0,
    scontoFornitoreNonOriginale: 5,
  },
  {
    id: "r19",
    marca: "Bucher",
    codiceFornitoreOriginale: "2000-4481",
    descrizione: "Guarnizione coperchio vasca idraulica",
    note: "Kit viti incluso",
    categoria: "Idraulica",
    compatibilitaMezzi: ["Bucher CityCat 2020", "Bucher CityCat 5006"],
    scorta: 15,
    scortaMinima: 6,
    dataUltimaModifica: now,
    autoreUltimaModifica: "Admin",
    prezzoFornitoreOriginale: 64.0,
    scontoFornitoreOriginale: 10,
    markupPercentuale: 64.06,
    prezzoVendita: rv(64.0, 64.06),
    fornitoreNonOriginale: "Elring",
    codiceFornitoreNonOriginale: "EL-4481-K",
    prezzoFornitoreNonOriginale: 52.0,
    scontoFornitoreNonOriginale: 8,
  },
  {
    id: "r20",
    marca: "Schmidt",
    codiceFornitoreOriginale: "S-884120",
    descrizione: "Spazzola centrale polipropilene 900mm",
    note: "Coppia bulloni M12",
    categoria: "Spazzole",
    compatibilitaMezzi: ["Schmidt Cleango 500", "Schmidt Swingo"],
    scorta: 6,
    scortaMinima: 4,
    dataUltimaModifica: now,
    autoreUltimaModifica: "Admin",
    prezzoFornitoreOriginale: 420.0,
    scontoFornitoreOriginale: 12,
    markupPercentuale: 47.62,
    prezzoVendita: rv(420.0, 47.62),
    fornitoreNonOriginale: "RAVO Parts",
    codiceFornitoreNonOriginale: "RB-900-PP",
    prezzoFornitoreNonOriginale: 368.0,
    scontoFornitoreNonOriginale: 9,
  },
  {
    id: "r21",
    marca: "Dulevo",
    codiceFornitoreOriginale: "DLV-90321",
    descrizione: "Getto acqua alta pressione ceramica",
    note: "",
    categoria: "Lavaggio",
    compatibilitaMezzi: ["Dulevo 6000 Revolution", "Dulevo 5000"],
    scorta: 8,
    scortaMinima: 3,
    dataUltimaModifica: now,
    autoreUltimaModifica: "Admin",
    prezzoFornitoreOriginale: 198.0,
    scontoFornitoreOriginale: 11,
    markupPercentuale: 54.04,
    prezzoVendita: rv(198.0, 54.04),
    fornitoreNonOriginale: "Kärcher Municipal",
    codiceFornitoreNonOriginale: "KM-HP-321",
    prezzoFornitoreNonOriginale: 175.0,
    scontoFornitoreNonOriginale: 8,
  },
  {
    id: "r22",
    marca: "Faun",
    codiceFornitoreOriginale: "FJ-77102",
    descrizione: "Giunto cardanico aspirazione",
    note: "Grasso speciale incluso",
    categoria: "Trasmissione",
    compatibilitaMezzi: ["Faun Viajet 6", "Mercedes Actros"],
    scorta: 4,
    scortaMinima: 2,
    dataUltimaModifica: now,
    autoreUltimaModifica: "Admin",
    prezzoFornitoreOriginale: 512.0,
    scontoFornitoreOriginale: 9,
    markupPercentuale: 45.51,
    prezzoVendita: rv(512.0, 45.51),
    fornitoreNonOriginale: "GKN",
    codiceFornitoreNonOriginale: "GU-77102-E",
    prezzoFornitoreNonOriginale: 460.0,
    scontoFornitoreNonOriginale: 7,
  },
  {
    id: "r23",
    marca: "Siemens",
    codiceFornitoreOriginale: "A2C53377433",
    descrizione: "Centralina NOx sensore downstream",
    note: "Calibrazione con diagnosi",
    categoria: "Elettronica",
    compatibilitaMezzi: ["Mercedes Actros", "Iveco Stralis"],
    scorta: 2,
    scortaMinima: 2,
    dataUltimaModifica: now,
    autoreUltimaModifica: "Admin",
    prezzoFornitoreOriginale: 640.0,
    scontoFornitoreOriginale: 6,
    markupPercentuale: 39.84,
    prezzoVendita: rv(640.0, 39.84),
    fornitoreNonOriginale: "Continental",
    codiceFornitoreNonOriginale: "5WK97344",
    prezzoFornitoreNonOriginale: 590.0,
    scontoFornitoreNonOriginale: 5,
  },
  {
    id: "r24",
    marca: "Garmin",
    codiceFornitoreOriginale: "FMI-7HV2",
    descrizione: "Antenna GNSS per telemetria flotta",
    note: "Montaggio cabina",
    categoria: "Elettronica",
    compatibilitaMezzi: ["Iveco Daily", "Mercedes Atego", "Schmidt Cleango 500"],
    scorta: 10,
    scortaMinima: 4,
    dataUltimaModifica: now,
    autoreUltimaModifica: "Admin",
    prezzoFornitoreOriginale: 132.0,
    scontoFornitoreOriginale: 14,
    markupPercentuale: 59.09,
    prezzoVendita: rv(132.0, 59.09),
    fornitoreNonOriginale: "Teltonika",
    codiceFornitoreNonOriginale: "TMT250-ANT",
    prezzoFornitoreNonOriginale: 98.0,
    scontoFornitoreNonOriginale: 10,
  },
  /** Coppia con stesso codice OE normalizzato (spazi/case) — per test controllo duplicati archivio */
  {
    id: "r-dup-a",
    marca: "TestParts",
    codiceFornitoreOriginale: "ARCH-DUP-001",
    descrizione: "Ricambio test duplicato archivio — variante A",
    note: "",
    categoria: "Diagnostica",
    compatibilitaMezzi: ["Iveco Daily"],
    scorta: 2,
    scortaMinima: 1,
    dataUltimaModifica: now,
    autoreUltimaModifica: "Admin",
    prezzoFornitoreOriginale: 10.0,
    scontoFornitoreOriginale: 0,
    markupPercentuale: 50,
    prezzoVendita: rv(10.0, 50),
    fornitoreNonOriginale: "",
    codiceFornitoreNonOriginale: "",
    prezzoFornitoreNonOriginale: 0,
    scontoFornitoreNonOriginale: 0,
  },
  {
    id: "r-dup-b",
    marca: "TestParts",
    codiceFornitoreOriginale: "  arch-dup  001 ",
    descrizione: "Ricambio test duplicato archivio — variante B",
    note: "",
    categoria: "Diagnostica",
    compatibilitaMezzi: ["Iveco Daily"],
    scorta: 1,
    scortaMinima: 1,
    dataUltimaModifica: now,
    autoreUltimaModifica: "Admin",
    prezzoFornitoreOriginale: 10.0,
    scontoFornitoreOriginale: 0,
    markupPercentuale: 50,
    prezzoVendita: rv(10.0, 50),
    fornitoreNonOriginale: "",
    codiceFornitoreNonOriginale: "",
    prezzoFornitoreNonOriginale: 0,
    scontoFornitoreNonOriginale: 0,
  },
];
