import type { MezzoGestito } from "@/lib/mezzi/types";

export const MEZZI_INITIAL_LISTE = {
  clienti: [
    "ASM Monza Brianza",
    "A2A Ambiente",
    "Hera S.p.A.",
    "Contarina",
    "Alia Servizi",
    "IAS Latina",
    "AMSA Milano",
    "Suez Italia",
    "Veritas Venezia",
    "ACEA Pinerolese",
    "AMIU Bari",
    "Comune di Lecce",
    "AGER Puglia",
    "Navita Barletta",
  ],
  marche: ["Iveco", "Mercedes-Benz", "Isuzu", "Bucher", "Schmidt", "Piaggio", "Renault", "Volvo", "Scania", "MAN"],
  tipiAttrezzatura: [
    "Spazzatrice stradale",
    "Compattatore rifiuti",
    "Autospazzatrice cabinata",
    "Lavastrade",
    "Ape raccolta rifiuti",
    "Ape spazzatrice",
    "Scarrabile",
    "Porter elettrico",
    "Multicarro",
    "Semirimorchio",
    "Motrice 4 assi",
    "Officina mobile",
  ],
  stati: ["Operativo", "In manutenzione", "Fermo amministrativo", "Attesa ricambi", "In collaudo"],
} as const;

/** 22 mezzi demo — 5 allineati a INITIAL_LAVORAZIONI (targa/matricola/macchina). */
export const MOCK_MEZZI: MezzoGestito[] = [
  {
    id: "mezzo-bucher-cc",
    lavorazioneMezzoId: "lav-201",
    cliente: "AMIU Bari",
    utilizzatore: "Servizio igiene urbana — Bari",
    marca: "Bucher",
    modello: "CityCat 5006",
    targa: "GA702XM",
    matricola: "CC5006-88291",
    numeroScuderia: "12",
    tipoAttrezzatura: "Lavastrade",
    anno: 2019,
    oreKm: 41200,
    statoAttuale: "In manutenzione",
    dataUltimaUscita: "2026-05-01",
    note: "Allineato a lavorazione attiva demo.",
    priorita: "alta",
  },
  {
    id: "mezzo-schmidt-sw",
    lavorazioneMezzoId: "lav-202",
    cliente: "Comune di Lecce",
    utilizzatore: "Cantiere mobilità — Lecce",
    marca: "Schmidt",
    modello: "Swingo 200+",
    targa: "LE334YZ",
    matricola: "SW200P-44102",
    tipoAttrezzatura: "Autospazzatrice cabinata",
    anno: 2020,
    oreKm: 67800,
    statoAttuale: "Attesa ricambi",
    dataUltimaUscita: "2026-04-26",
    note: "Storico revisione su dati Lavorazioni.",
    priorita: "media",
  },
  {
    id: "mezzo-iveco-mob",
    lavorazioneMezzoId: "lav-203",
    cliente: "AGER Puglia",
    utilizzatore: "Manutenzione programmata flotta",
    marca: "Iveco",
    modello: "Daily Officina Mobile",
    targa: "BT901LK",
    matricola: "OM-55231",
    tipoAttrezzatura: "Officina mobile",
    anno: 2021,
    oreKm: 28000,
    statoAttuale: "Operativo",
    dataUltimaUscita: "2026-05-03",
    note: "",
    priorita: "normale",
  },
  {
    id: "mezzo-merc-eco",
    lavorazioneMezzoId: "lav-204",
    cliente: "Navita Barletta",
    utilizzatore: "Raccolta rifiuti urbani",
    marca: "Mercedes-Benz",
    modello: "Econic compattatore",
    targa: "BA445TR",
    matricola: "ME-ECO-77812",
    tipoAttrezzatura: "Compattatore rifiuti",
    anno: 2018,
    oreKm: 156400,
    statoAttuale: "Operativo",
    dataUltimaUscita: "2026-05-06",
    note: "",
    priorita: "alta",
  },
  {
    id: "mezzo-scarab",
    lavorazioneMezzoId: "lav-205",
    cliente: "AMIU Bari",
    utilizzatore: "Spazzamento meccanizzato",
    marca: "Scarab",
    modello: "Minor",
    targa: "BT228NN",
    matricola: "SC-MIN-22901",
    tipoAttrezzatura: "Spazzatrice stradale",
    anno: 2017,
    oreKm: 52000,
    statoAttuale: "Operativo",
    dataUltimaUscita: "2026-05-09",
    note: "",
    priorita: "media",
  },
  {
    id: "mezzo-06",
    cliente: "ASM Monza Brianza",
    utilizzatore: "Cantiere Nord",
    marca: "Iveco",
    modello: "Daily 70C15",
    targa: "GB412NM",
    matricola: "IV-DLY-2019-00412",
    tipoAttrezzatura: "Compattatore rifiuti",
    anno: 2019,
    oreKm: 84200,
    statoAttuale: "Operativo",
    dataUltimaUscita: "2026-05-02",
    note: "Telemetria flotta.",
    priorita: "normale",
  },
  {
    id: "mezzo-07",
    cliente: "A2A Ambiente",
    utilizzatore: "Logistica Est",
    marca: "Mercedes-Benz",
    modello: "Econic 1829",
    targa: "FL229KD",
    matricola: "MB-ECO-2018-00229",
    tipoAttrezzatura: "Spazzatrice stradale",
    anno: 2018,
    oreKm: 198000,
    statoAttuale: "Operativo",
    dataUltimaUscita: "2026-04-01",
    note: "",
    priorita: "normale",
  },
  {
    id: "mezzo-08",
    cliente: "Hera S.p.A.",
    utilizzatore: "Impianto BO Nord",
    marca: "Isuzu",
    modello: "NPR 75",
    targa: "DY881LP",
    matricola: "IS-NPR-2020-00881",
    tipoAttrezzatura: "Autospazzatrice cabinata",
    anno: 2020,
    oreKm: 92300,
    statoAttuale: "Operativo",
    dataUltimaUscita: "2026-04-01",
    note: "",
    priorita: "media",
  },
  {
    id: "mezzo-09",
    cliente: "Contarina",
    utilizzatore: "Turno notte",
    marca: "Bucher",
    modello: "CityCat 2020",
    targa: "GD903WW",
    matricola: "BC-CT20-2017-00903",
    tipoAttrezzatura: "Lavastrade",
    anno: 2017,
    oreKm: 41200,
    statoAttuale: "Operativo",
    dataUltimaUscita: "2026-03-05",
    note: "Serbatoio acqua alta pressione.",
    priorita: "normale",
  },
  {
    id: "mezzo-10",
    cliente: "Alia Servizi",
    utilizzatore: "Firenze urbano",
    marca: "Schmidt",
    modello: "Cleango 500",
    targa: "FA112TX",
    matricola: "SC-CG5-2021-00112",
    tipoAttrezzatura: "Spazzatrice stradale",
    anno: 2021,
    oreKm: 28900,
    statoAttuale: "Attesa ricambi",
    dataUltimaUscita: "2026-05-01",
    note: "Centralina NOx.",
    priorita: "alta",
  },
  {
    id: "mezzo-11",
    cliente: "IAS Latina",
    utilizzatore: "Raccolta centro",
    marca: "Piaggio",
    modello: "Porter NP6",
    targa: "EW554JJ",
    matricola: "PG-PRT-2022-00554",
    tipoAttrezzatura: "Porter elettrico",
    anno: 2022,
    oreKm: 12400,
    statoAttuale: "Operativo",
    dataUltimaUscita: "2026-04-22",
    note: "BMS batteria.",
    priorita: "normale",
  },
  {
    id: "mezzo-12",
    cliente: "AMSA Milano",
    utilizzatore: "Quartiere Ovest",
    marca: "Iveco",
    modello: "Eurocargo ML120",
    targa: "GF221MZ",
    matricola: "IV-ECG-2016-00221",
    tipoAttrezzatura: "Ape raccolta rifiuti",
    anno: 2016,
    oreKm: 198000,
    statoAttuale: "Fermo amministrativo",
    dataUltimaUscita: "2025-12-20",
    note: "Revisione da pianificare.",
    priorita: "media",
  },
  {
    id: "mezzo-13",
    cliente: "Suez Italia",
    utilizzatore: "Hub Torino",
    marca: "Iveco",
    modello: "Stralis AD260",
    targa: "GT884PL",
    matricola: "IV-STR-2015-00884",
    tipoAttrezzatura: "Scarrabile",
    anno: 2015,
    oreKm: 512000,
    statoAttuale: "Operativo",
    dataUltimaUscita: "2026-01-25",
    note: "",
    priorita: "normale",
  },
  {
    id: "mezzo-14",
    cliente: "Veritas Venezia",
    utilizzatore: "Isola ecologica Mestre",
    marca: "Schmidt",
    modello: "Swingo 200+",
    targa: "GE667RR",
    matricola: "SC-SW2-2019-00667",
    tipoAttrezzatura: "Autospazzatrice cabinata",
    anno: 2019,
    oreKm: 67800,
    statoAttuale: "In collaudo",
    dataUltimaUscita: "2026-05-09",
    note: "ABS post-intervento.",
    priorita: "media",
  },
  {
    id: "mezzo-15",
    cliente: "ACEA Pinerolese",
    utilizzatore: "Cantiere stradale",
    marca: "Volvo",
    modello: "FE 320",
    targa: "CN334SS",
    matricola: "VL-FE3-2018-00334",
    tipoAttrezzatura: "Motrice 4 assi",
    anno: 2018,
    oreKm: 223400,
    statoAttuale: "Operativo",
    dataUltimaUscita: "2026-04-12",
    note: "",
    priorita: "normale",
  },
  {
    id: "mezzo-16",
    cliente: "ASM Monza Brianza",
    utilizzatore: "Parcheggi interrati",
    marca: "Piaggio",
    modello: "Ape Classic",
    targa: "EB901AA",
    matricola: "PG-APE-2014-00901",
    tipoAttrezzatura: "Ape spazzatrice",
    anno: 2014,
    oreKm: 45600,
    statoAttuale: "Operativo",
    dataUltimaUscita: "2025-11-22",
    note: "Spazzola 900 mm.",
    priorita: "normale",
  },
  {
    id: "mezzo-17",
    cliente: "A2A Ambiente",
    utilizzatore: "Impianto compost",
    marca: "Bucher",
    modello: "CityCat 5006",
    targa: "FH778BB",
    matricola: "BC-CT56-2020-00778",
    tipoAttrezzatura: "Lavastrade",
    anno: 2020,
    oreKm: 33100,
    statoAttuale: "Operativo",
    dataUltimaUscita: "2026-04-18",
    note: "",
    priorita: "normale",
  },
  {
    id: "mezzo-18",
    cliente: "Contarina",
    utilizzatore: "Treviso città",
    marca: "Mercedes-Benz",
    modello: "Atego 1524",
    targa: "TV228DD",
    matricola: "MB-ATG-2017-00228",
    tipoAttrezzatura: "Compattatore rifiuti",
    anno: 2017,
    oreKm: 134200,
    statoAttuale: "Operativo",
    dataUltimaUscita: "2026-03-01",
    note: "",
    priorita: "media",
  },
  {
    id: "mezzo-19",
    cliente: "Alia Servizi",
    utilizzatore: "Prato nord",
    marca: "Renault",
    modello: "Midlum 220",
    targa: "PO339EE",
    matricola: "RN-MDL-2016-00339",
    tipoAttrezzatura: "Multicarro",
    anno: 2016,
    oreKm: 178900,
    statoAttuale: "Attesa ricambi",
    dataUltimaUscita: "2026-04-30",
    note: "",
    priorita: "media",
  },
  {
    id: "mezzo-20",
    cliente: "IAS Latina",
    utilizzatore: "Aprilia",
    marca: "Scania",
    modello: "P 320",
    targa: "LT556FF",
    matricola: "SC-P32-2018-00556",
    tipoAttrezzatura: "Semirimorchio",
    anno: 2018,
    oreKm: 401200,
    statoAttuale: "Operativo",
    dataUltimaUscita: "2025-10-05",
    note: "Tachigrafo.",
    priorita: "normale",
  },
  {
    id: "mezzo-21",
    cliente: "Contarina",
    utilizzatore: "Padova sud",
    marca: "Iveco",
    modello: "Daily 50C15",
    targa: "PD001MM",
    matricola: "IV-DLY-2018-00001",
    tipoAttrezzatura: "Ape spazzatrice",
    anno: 2018,
    oreKm: 72100,
    statoAttuale: "Fermo amministrativo",
    dataUltimaUscita: "2025-08-15",
    note: "Assicurativo.",
    priorita: "alta",
  },
  {
    id: "mezzo-22",
    cliente: "Hera S.p.A.",
    utilizzatore: "Bologna",
    marca: "Mercedes-Benz",
    modello: "Econic 2630",
    targa: "BO112NN",
    matricola: "MB-ECO-2020-00112",
    tipoAttrezzatura: "Compattatore rifiuti",
    anno: 2020,
    oreKm: 68900,
    statoAttuale: "Operativo",
    dataUltimaUscita: "2026-05-03",
    note: "Telemetria OEM.",
    priorita: "normale",
  },
];
