import type { LavorazioneArchiviata, LavorazioneAttiva, StatoLavorazioneConfig } from "@/lib/lavorazioni/types";

/** Id dello stato "Completata" — usato per abilitare archiviazione. */
export const LAVORAZIONE_STATO_COMPLETATA_ID = "lav-stato-completata";

export const DEFAULT_STATI_LAVORAZIONI: StatoLavorazioneConfig[] = [
  { id: "lav-stato-accettazione", label: "Accettazione" },
  { id: "lav-stato-att-prev", label: "Attesa preventivo" },
  { id: "lav-stato-att-ricambi", label: "Attesa ricambi" },
  { id: "lav-stato-da-lavorare", label: "Da lavorare" },
  { id: "lav-stato-in-lavorazione", label: "In lavorazione" },
  { id: LAVORAZIONE_STATO_COMPLETATA_ID, label: "Compl." },
];

export const DEFAULT_ADDETTI_LAVORAZIONI: string[] = [
  "Marco Rossi",
  "Luca Bianchi",
  "Giuseppe Romano",
  "Antonio Greco",
];

export const INITIAL_LAVORAZIONI_ATTIVE: LavorazioneAttiva[] = [
  {
    id: "lav-201",
    macchina: "Bucher CityCat 5006",
    targa: "GA702XM",
    matricola: "CC5006-88291",
    nScuderia: "12",
    cliente: "AMIU Bari",
    utilizzatore: "Servizio igiene urbana — Bari",
    cantiere: "",
    statoId: "lav-stato-in-lavorazione",
    priorita: "alta",
    addetto: "Marco Rossi",
    noteInterne: "Sostituzione pompa idraulica — ricambi ordinati.",
    dataIngresso: "2026-05-01T07:30:00.000Z",
    dataCompletamento: null,
  },
  {
    id: "lav-202",
    macchina: "Schmidt Swingo 200+",
    targa: "LE334YZ",
    matricola: "SW200P-44102",
    nScuderia: "",
    cliente: "Comune di Lecce",
    utilizzatore: "Ufficio tecnico mobilità",
    cantiere: "Mobilità urbana — Lecce",
    statoId: "lav-stato-att-ricambi",
    priorita: "media",
    addetto: "Luca Bianchi",
    noteInterne: "In attesa guarnizioni originali Schmidt.",
    dataIngresso: "2026-04-26T09:00:00.000Z",
    dataCompletamento: null,
  },
  {
    id: "lav-203",
    macchina: "Iveco Daily Officina Mobile",
    targa: "BT901LK",
    matricola: "OM-55231",
    nScuderia: "",
    cliente: "AGER Puglia",
    utilizzatore: "Manutenzione programmata flotta",
    cantiere: "",
    statoId: "lav-stato-att-prev",
    priorita: "bassa",
    addetto: "Giuseppe Romano",
    noteInterne: "Preventivo inviato 28/04, in attesa autorizzazione.",
    dataIngresso: "2026-05-03T08:15:00.000Z",
    dataCompletamento: null,
  },
  {
    id: "lav-204",
    macchina: "Mercedes Econic compattatore",
    targa: "BA445TR",
    matricola: "ME-ECO-77812",
    nScuderia: "",
    cliente: "Navita Barletta",
    utilizzatore: "Raccolta rifiuti urbani",
    cantiere: "",
    statoId: "lav-stato-da-lavorare",
    priorita: "alta",
    addetto: "Antonio Greco",
    noteInterne: "Mezzo fermo — verifica pressione circuito.",
    dataIngresso: "2026-05-06T06:45:00.000Z",
    dataCompletamento: null,
  },
  {
    id: "lav-205",
    macchina: "Scarab Minor",
    targa: "BT228NN",
    matricola: "SC-MIN-22901",
    nScuderia: "",
    cliente: "AMIU Bari",
    utilizzatore: "Spazzamento meccanizzato",
    cantiere: "",
    statoId: "lav-stato-accettazione",
    priorita: "media",
    addetto: "Marco Rossi",
    noteInterne: "Ingresso per controllo programmato 12 mesi.",
    dataIngresso: "2026-05-09T10:00:00.000Z",
    dataCompletamento: null,
  },
];

export const INITIAL_LAVORAZIONI_STORICO: LavorazioneArchiviata[] = [
  {
    id: "lav-arch-101",
    macchina: "Schmidt Swingo 200+",
    targa: "LE334YZ",
    matricola: "SW200P-44102",
    nScuderia: "",
    cliente: "Comune di Lecce",
    utilizzatore: "Ufficio tecnico mobilità",
    cantiere: "Mobilità urbana — Lecce",
    addetto: "Luca Bianchi",
    noteInterne: "Chiusura revisione periodica.",
    statoFinaleId: LAVORAZIONE_STATO_COMPLETATA_ID,
    prioritaFinale: "alta",
    dataIngresso: "2026-04-02T08:00:00.000Z",
    dataCompletamento: "2026-04-05T15:30:00.000Z",
    meseCompletamento: "2026-04",
  },
  {
    id: "lav-arch-102",
    macchina: "Bucher CityCat 5006",
    targa: "GA702XM",
    matricola: "CC5006-88291",
    nScuderia: "12",
    cliente: "AGER Puglia",
    utilizzatore: "Manutenzione programmata flotta",
    cantiere: "",
    addetto: "Giuseppe Romano",
    noteInterne: "Intervento chiuso in officina.",
    statoFinaleId: LAVORAZIONE_STATO_COMPLETATA_ID,
    prioritaFinale: "media",
    dataIngresso: "2026-04-10T07:00:00.000Z",
    dataCompletamento: "2026-04-18T11:00:00.000Z",
    meseCompletamento: "2026-04",
  },
  {
    id: "lav-arch-103",
    macchina: "Scarab Minor",
    targa: "BT228NN",
    matricola: "SC-MIN-22901",
    nScuderia: "",
    cliente: "Navita Barletta",
    utilizzatore: "Spazzamento meccanizzato",
    cantiere: "",
    addetto: "Antonio Greco",
    noteInterne: "Riparazione rapida uscita giornaliera.",
    statoFinaleId: LAVORAZIONE_STATO_COMPLETATA_ID,
    prioritaFinale: "bassa",
    dataIngresso: "2026-03-05T09:30:00.000Z",
    dataCompletamento: "2026-03-06T18:00:00.000Z",
    meseCompletamento: "2026-03",
  },
];
